[pytest]
addopts = --slowmo 50 --html=../reports/report.html --self-contained-html
log_cli = true
log_level = DEBUG
markers =
    ui_health_check: Ui health_check test cases
    api_health_check: API health_check test cases
    e2e_health_check: hybrid end-to-end test cases
